feat(observer): data sampling using random ranges
ar-io/ar-io-observer pull request #31
Opened 2024-03-06 20:33 UTC by karlprieb

When data is bigger than 1MiB `getArnsResolution` will hash 5 random 200 bytes. The randomness is generated through a shared entropy (based on epoch start height) that changes at each contract epoch.

2024-03-07 15:40 UTC, djwhitt requested changes
I think we should tweak the RNG algorithm slightly (see inline comments). Also, I'm seeing stuff like this when I try to run the report:

```
          "connect": {
            "assessedAt": 1709825722,
            "expectedId": null,
            "resolvedId": null,
            "expectedDataHash": null,
            "resolvedDataHash": null,
            "failureReason": "Content length is not defined",
            "pass": false
          }
```

That should at least have an `expectedId`. Are you getting valid reports when you run  `yarn observe`?

2024-03-07 15:40 UTC, djwhitt commented on src/observer.ts
> +    const result = seed[index % seed.length];
This will wrap around if we run out of values in the array, right? Could create a hash chain based version instead? For each new number requested create a single floating point value based on the current hash, hash the current hash, and use that new hash next time.

2024-03-07 15:40 UTC, djwhitt commented on src/observer.ts
> +            dataHash.update(response.body);
Is the body we get back here a buffer?

2024-03-08 19:15 UTC, karlprieb commented on src/observer.ts
> +    const result = seed[index % seed.length];
Done

2024-03-08 19:17 UTC, karlprieb commented on src/observer.ts
> +            dataHash.update(response.body);
Yes, we set `responseType: 'buffer'` here https://github.com/ar-io/ar-io-observer/blob/1eebb391de8c9fb31c8174c046f793f4a37f0646/src/observer.ts#L187-L192 and `got` does to work for us :)

2024-03-08 20:36 UTC, djwhitt approved these changes
Nice work!

2024-03-08 20:36 UTC, djwhitt commented on src/observer.ts
> +            dataHash.update(response.body);
Ah, missed that. Thanks!

2024-03-08 20:37 UTC, merged